POST http://localhost:5258/api/v1/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzZTI2YWM2Mi01YTE5LTQ3NjktODI0ZC1mYzMwMWY2MzY3MzIiLCJyb2xlIjoiQ3VzdG9tZXIiLCJlbWFpbCI6Im1hcmlhQG1haWwuY29tIiwibmJmIjoxNzAzNjkxODIyLCJleHAiOjE3MDM4NjQ2MjIsImlhdCI6MTcwMzY5MTgyMiwiaXNzIjoiUGhhdCIsImF1ZCI6IlBoYXRFQ29tbWVyY2UifQ.LYD2rUm28B_ipQ32d_MTaBxWUpy-ZX0GO1b5a6iktNY
Content-Type: application/json

{
  "orderProducts": [
    {
      "productId": "6ee34de1-133d-4433-96ba-ab62696bc7ba",
      "quantity": 20
    }
  ],
  "orderStatus": "Pending"
}

###
GET http://localhost:5258/api/v1/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlYjliOWFhYS02MzYwLTRkZWEtYWQzNy0wNGFhZjA4MDVlOTQiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIiwibmJmIjoxNzAzNjYyNTM3LCJleHAiOjE3MDM4MzUzMzcsImlhdCI6MTcwMzY2MjUzNywiaXNzIjoiUGhhdCIsImF1ZCI6IlBoYXRFQ29tbWVyY2UifQ.b1EaxeZiVruALzroxwc9H7aGeLRzwh-FWQQwBxlQnMg

###
GET http://localhost:5258/api/v1/orders/30eba6d7-e45c-4d6a-a40f-569d45f5508f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzZTI2YWM2Mi01YTE5LTQ3NjktODI0ZC1mYzMwMWY2MzY3MzIiLCJyb2xlIjoiQ3VzdG9tZXIiLCJlbWFpbCI6Im1hcmlhQG1haWwuY29tIiwibmJmIjoxNzAzNjkxODIyLCJleHAiOjE3MDM4NjQ2MjIsImlhdCI6MTcwMzY5MTgyMiwiaXNzIjoiUGhhdCIsImF1ZCI6IlBoYXRFQ29tbWVyY2UifQ.LYD2rUm28B_ipQ32d_MTaBxWUpy-ZX0GO1b5a6iktNY

###
GET http://localhost:5258/api/v1/orders/user/0cf0f8e7-6292-408e-87ac-fad7c906d72c HTTP/1.1

###
DELETE http://localhost:5258/api/v1/orders/0d0e512d-5714-4612-afa3-7997336759fc HTTP/1.1

###
PATCH http://localhost:5258/api/v1/orders/a9c113b7-398e-4883-871b-2ddfb4570036 HTTP/1.1
Content-Type: application/json

{
  "OrderStatus": "Shipping"
}