GET http://localhost:5258/api/v1/products HTTP/1.1

###
GET http://localhost:5258/api/v1/products/7a9f4623-a0af-4d00-87fd-ec6b379941c8 HTTP/1.1

###
POST http://localhost:5258/api/v1/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJjMDc4ZTQzYy03ZDA5LTQ0ZjAtOGI1OS0wMzNhMTg5MDJkNDgiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIiwibmJmIjoxNzAzNzUyOTI0LCJleHAiOjE3MDM5MjU3MjQsImlhdCI6MTcwMzc1MjkyNCwiaXNzIjoiUGhhdCIsImF1ZCI6IlBoYXRFQ29tbWVyY2UifQ.2Q7dn60HDiepLPx-7gIVi4uYNFWQmXJ78qkj47bJy04
Content-Type: application/json

{
  "inventory": 100,
  "title": "Razer Blade",
  "price": 1500,
  "description": "expensive",
  "categoryId": "b6ca78a9-37fd-4ad7-ae19-94108cd09654",
  "images": [
    {
      "url": "https://picsum.photos/200"
    }
  ]
}

###
PATCH http://localhost:5258/api/v1/products/704f67c6-7b5d-4250-acca-1ef4dc655a07 HTTP/1.1
Content-Type: application/json

{
  "inventory": 500,
  "title": "fanny bag",
  "price": 90,
  "description": "looks fancy",
  "categoryId": "01e6b770-207c-40e2-8f4a-fcf9253d8a04",
  "images": [
    {
      "url": "https://picsum.photos/200"
    }
  ]
}

###
DELETE http://localhost:5258/api/v1/products/f01fe6d8-d1f9-4c28-8118-3ab541dbf97f HTTP/1.1
