POST http://localhost:5258/api/v1/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2YmUwYmRhZC0wYzAxLTRiMzUtYjhlYS04ZmFjMGJkOTg5MDgiLCJyb2xlIjoiQ3VzdG9tZXIiLCJlbWFpbCI6Im1hcmlhQG1haWwuY29tIiwibmJmIjoxNzAzNzUzMTQ0LCJleHAiOjE3MDM5MjU5NDQsImlhdCI6MTcwMzc1MzE0NCwiaXNzIjoiUGhhdCIsImF1ZCI6IlBoYXRFQ29tbWVyY2UifQ.4uKoDUMxUlpJxdB4_wdYu1NJpk-6-nKyTh0iehwboYw

{
  "rating": 3,
  "content": "good",
  "productID": "5993dbdf-4b60-4ca6-b068-655e02179119"
}

###
GET http://localhost:5258/api/v1/reviews HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlYjliOWFhYS02MzYwLTRkZWEtYWQzNy0wNGFhZjA4MDVlOTQiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIiwibmJmIjoxNzAzMzU4NTMxLCJleHAiOjE3MDM1MzEzMzEsImlhdCI6MTcwMzM1ODUzMSwiaXNzIjoiUGhhdCIsImF1ZCI6IlBoYXRFQ29tbWVyY2UifQ.MvcqTi__CbKm89L5O4EKvRCu0pA6wAgrEjN-rSybR30

###
GET http://localhost:5258/api/v1/reviews/a4ea088d-f752-48d6-8929-c77bee70d853 HTTP/1.1