POST http://localhost:5258/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "name": "jim",
  "email": "jim2qwdqwd@gmail.com",
  "password": "string2wqdqwedq2w",
  "avatar": "www.jim.com",
  "role": "Admin",
  "addresses": [
    {
      "houseNumber": 68,
      "street": "tqk",
      "postCode": 61
    }
  ]
}

###
GET http://localhost:5258/api/v1/auth/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJiZGYyYmZhOC0zNDU5LTRhMjAtYjU0Yi04Njg0ZWFjNTczYTYiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6ImppbUBtYWlsLmNvbSIsIm5iZiI6MTcwMzE3NTc3NCwiZXhwIjoxNzAzMzQ4NTc0LCJpYXQiOjE3MDMxNzU3NzQsImlzcyI6IlBoYXQiLCJhdWQiOiJQaGF0RUNvbW1lcmNlIn0.iALRVDPfyL_nYAfX24ZzDIhDA19DAWnosJzVdL1Z7oo

###
POST http://localhost:5258/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "jim@mail.com",
  "password": "1234"
}