POST http://localhost:5258/api/v1/orders HTTP/1.1
Content-Type: application/json

{
  "userId": "0cf0f8e7-6292-408e-87ac-fad7c906d72c",
  "orderProducts": [
    {
      "productId": "704f67c6-7b5d-4250-acca-1ef4dc655a07",
      "quantity": 4
    }
  ],
  "orderStatus": "Pending"
}

###
GET http://localhost:5258/api/v1/orders/ HTTP/1.1

###
DELETE http://localhost:5258/api/v1/orders/77a945b0-7321-4bea-aee8-1de7a362d35e HTTP/1.1