POST http://localhost:5258/api/v1/orders HTTP/1.1
Content-Type: application/json

{
  "userId": "f426fab5-3e4d-4219-afad-a32e5c626eda",
  "orderProducts": [
    {
      "productId": "fcd28e8f-9973-475e-a47e-3c7ceef1a575",
      "quantity": 4
    }
  ],
  "orderStatus": "Pending"
}