POST http://localhost:5258/api/v1/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJmZmYxNzM2NC0zYjE3LTQwMGMtOTkwNy01OTM0MTNmZmIyNjAiLCJyb2xlIjoiQ3VzdG9tZXIiLCJlbWFpbCI6Im1hcmlhQG1haWwuY29tIiwibmJmIjoxNzAzNTM2Mjg0LCJleHAiOjE3MDM3MDkwODQsImlhdCI6MTcwMzUzNjI4NCwiaXNzIjoiUGhhdCIsImF1ZCI6IlBoYXRFQ29tbWVyY2UifQ.GlesCKneE75Wsh168yFkhVfoRTN9tzMQ7oIXlZB07nU
Content-Type: application/json

{
  "userId": "fff17364-3b17-400c-9907-593413ffb260",
  "orderProducts": [
    {
      "productId": "90c065b8-b8a0-43d1-8cba-dc517f209a91",
      "quantity": 20
    }
  ],
  "orderStatus": "Pending"
}

###
GET http://localhost:5258/api/v1/orders/ HTTP/1.1

###
GET http://localhost:5258/api/v1/orders/a9c113b7-398e-4883-871b-2ddfb4570036 HTTP/1.1

###
GET http://localhost:5258/api/v1/orders/user/0cf0f8e7-6292-408e-87ac-fad7c906d72c HTTP/1.1

###
DELETE http://localhost:5258/api/v1/orders/0d0e512d-5714-4612-afa3-7997336759fc HTTP/1.1

###
PATCH http://localhost:5258/api/v1/orders/a9c113b7-398e-4883-871b-2ddfb4570036 HTTP/1.1
Content-Type: application/json

{
  "OrderStatus": "Shipping"
}